- name: Excluir todas as chaves públicas e privadas.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ssh-key

- name: Criando diretório ssh-key
  shell: mkdir {{ playbook_dir }}/ssh-key

- name: generate SSH key 
  openssh_keypair:
    path: "{{ playbook_dir }}/ssh-key/vm_key"
    type: rsa
    size: 4096
    state: present
    force: no
  delegate_to: localhost

- name: Excluir arquivo cloud-init existente.
  file:
    path: ./config/cloud-init.yaml
    state: absent

- name: Criando arquivo cloud-init e inserindo a chave ssh pública.
  template:
    src: ./templates/cloud-init-template.j2
    dest: ./config/cloud-init.yaml
  delegate_to: localhost
  vars:
    public_key: "{{lookup('file', './ssh-key/vm_key.pub')}}"
